version: '3.4'

services:
  ui.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Database__Server=database
      - ASPNETCORE_Database__Port=1433
      - ASPNETCORE_Database__Name=caretaker
      - ASPNETCORE_Database__User=sa
      - "ASPNETCORE_Database__Password=${DATABASE_PASSWORD}"
    ports:
      - "8080"
      - "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro