version: '3.4'

services:
  ui.api:
    image: ${DOCKER_REGISTRY-}caretaker.ui.api
    build:
      context: .
      dockerfile: Ui.Api/Dockerfile
    container_name: caretaker.api
    restart: on-failure
    depends_on:
      - database
    networks:
      - caretaker-network

  database:
    image: postgres:16.2-alpine
    container_name: caretaker.database
    restart: always
    networks:
      - caretaker-network

  adminer:
    image: adminer
    container_name: caretaker.adminer
    restart: always
    depends_on:
      - database
    networks:
      - caretaker-network

networks:
  caretaker-network:
    driver: bridge
